name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Or 'adopt', 'zulu', etc.
          cache: 'gradle' # Caches Gradle dependencies
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build # This will also run the 'test' task by default
      - name: Run Unit Tests
        run: ./gradlew test # Explicitly run the test task if 'build' doesn't cover it